//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeeinfo()
        {
            this.Bloginfoes = new HashSet<Bloginfo>();
        }
    
        public string emailid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<int> passcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloginfo> Bloginfoes { get; set; }
    }
}
