//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class capstonedbEntities : DbContext
    {
        public capstonedbEntities()
            : base("name=capstonedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bloginfo> Bloginfoes { get; set; }
        public virtual DbSet<employeeinfo> employeeinfoes { get; set; }
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
    }
}
